services:
  pi5bot:
    build: .
    container_name: pi5bot_container
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/apps/Pi5Bot
    env_file:
      - ./Pi5Bot/.env

    command: /bin/bash -c "python main.py"
    