version: '3.8'

services:
  pi5bot:
    build: .
    container_name: pi5bot_container
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:cd 
    command: /bin/bash -c "chmod +x /apps/Pi5Bot/pull_latest.sh && /apps/Pi5Bot/pull_latest.sh && python main.py"
    env_file:
      - /home/mehrain/Workspace/github.com/mehrain/Pi5Bot/.env